name: Deploy static website

on:
  push:
    branches:
      - gh-pages # or the branch you want to trigger the deploy

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Node.js 20
        uses: actions/setup-node@v3  # Explicitly set Node.js version to 20
        with:
          node-version: '20'

      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./public  # Path to your `/public` folder containing index.html, styles.css, and script.js
          force_orphan: true  # Ensures a clean deployment by using a fresh gh-pages branch each time
