name: Deploy to GitHub Pages

on:
  push:
    branches:
      - main  # Or the default branch of your repository

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout the repository
        uses: actions/checkout@v3

      - name: Install Node.js (for potential build steps)
        uses: actions/setup-node@v3
        with:
          node-version: '16'  # Use the appropriate Node.js version for your project

      - name: Build the project
        run: npm install && npm run build  # Only use if you have a build step, otherwise skip this

      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./public  # This is the folder you want to deploy
